### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by Phoenixnerd** [smashmyster/TurntApp#4]
Display user data. People following me, people am following. Load image from url using sampling and avoiding outofmemory exception.

**Comment by Percyenna** [comment]
There is a tab for attending, what is that?

**Comment by smashmyster** [comment]
It shows how many events you are going to be attending. When. You click on that tab, you will get a list of events you said you are attending

**Comment by Percyenna** [comment]
Ok, and then the google maps part, do we have a location for the event in the database?

**Comment by smashmyster** [comment]
The rest API receives latlong for each event. There is no need to format the data all you have to do is parse the values to the google maps intent. We are using Andries lamp sever. Check index.php for all the functions you can access
