### ISSUE TITLE
Parsing xml display from server 

### ISSUE THREAD

**Issue by Phoenixnerd** [smashmyster/TurntApp#5]
Get an xml file of a club and disply it on the UI

**Comment by Phoenixnerd** [comment]
@lesego-reezy  did you manage to create the xml display?

**Comment by lesego-reezy** [comment]
I can't figure it out. Do you have some examples?

**Comment by Phoenixnerd** [comment]
not really hey

**Comment by lesego-reezy** [comment]
@smashmyster bro do you have some template or something for the xml display? I can't figure it out.
